.TH "ACCcontrol" 3 "Version 1.0.0" "ACC" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ACCcontrol
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "float \fBAcceleration\fP"
.br
.ti -1c
.RI "float \fBSafe_distance\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "float Acceleration"

.SS "float Safe_distance"


.SH "Author"
.PP 
Generated automatically by Doxygen for ACC from the source code\&.
