.TH "ACCenable" 3 "Version 1.0.0" "ACC" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ACCenable
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "bool \fBACC_enabled\fP"
.br
.ti -1c
.RI "bool \fBaux\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "bool ACC_enabled"

.SS "bool aux"


.SH "Author"
.PP 
Generated automatically by Doxygen for ACC from the source code\&.
