name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install CUnit
      run:  sudo apt-get install libcunit1 libcunit1-doc libcunit1-dev
      
    - name: Build tests and coverage
      run: cd ACC_Code && make build
          
    - name: Run tests
      run:  cd ACC_Code && ./main
            
    - name: Run coverage
      run: cd ACC_Code && make coverage
      
    - name: Install html report labraries 
      run: sudo apt-get install lcov clang-format && pip install gcovr
      
    - name: Test and coverage report 
      run: mkdir gcovr-report && gcovr --root . --html --html-details --output gcovr-report/coverage.html
      
   
