name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: configure
      run: ./configure
    - name: Install CUnit
      run: sudo apt-get install libcunit1-dev
    - name: Build and Test
      run:  gcc -o test_suite Test_ACC.c -lcunit
            ./test_suite
      
   
